import {
  type LucideProps,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  Circle,
  CommandIcon as Command,
  FileTextIcon as FileText,
  GithubIcon as Github,
  HelpCircle,
  ImageIcon as Image,
  Laptop,
  Loader2,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings2,
  SunMedium,
  Trash2,
  TwitterIcon as Twitter,
  X,
  RefreshCw,
  Globe2,
  MenuIcon as Menu,
  AlertCircle,
  Download,
  Music2,
  BookOpen,
  Search,
  PlayCircle,
  Activity,
  Inbox,
  Languages,
  Tv2
} from "lucide-react";

export type Icon = React.ForwardRefExoticComponent<LucideProps>;

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  chevronsUpDown: ChevronDown,
  trash: Trash2,
  settings: Settings2,
  user: Circle,
  plus: Plus,
  menu: Menu,
  moon: Moon,
  sun: SunMedium,
  help: HelpCircle,
  pizza: Pizza,
  twitter: Twitter,
  check: Check,
  circle: Circle,
  file: FileText,
  fileText: FileText,
  image: Image,
  laptop: Laptop,
  moreVertical: MoreVertical,
  arrowRight: ArrowRight,
  refresh: RefreshCw,
  globe: Globe2,
  alert: AlertCircle,
  github: Github,
  download: Download,
  music: Music2,
  book: BookOpen,
  search: Search,
  play: PlayCircle,
  activity: Activity,
  inbox: Inbox,
  languages: Languages,
  tv: Tv2
};